### ISSUE TITLE
大佬你好! 我在使用你的插件的时候无法获取input的value, 请问用什么方法调用呢?

### ISSUE THREAD

**Issue by Whisper912** [FBmm/wui-date#1]
<div class="wui-area">
    <wui-date
                    format="yyyy-mm-dd hh:mm"
                    placeholder="请选择或输入日期"
                    id="date"
                    btns="{'ok':'确定','now':'此刻'}"
                    ng-model="date"
                    name="start"
      >
      </wui-date>
</div>

<script>
var inputs = document.getElementsByName('.wui-date');
var start=inputs[0];
console.log(start.value);
<script/>

**Comment by dnk19940305** [comment]
大佬你好 我想知道你这个插件在点击确认之后的时候有没有什么方法来输出返回值 还是只能通过另外事件来获取
